# Generated by Django 5.2.4 on 2025-10-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_options_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='privacy_status',
            field=models.CharField(choices=[('public', 'Публічний'), ('friends', 'Тільки друзі')], default='public', max_length=10, verbose_name='Статус конфіденційності'),
        ),
    ]
