# Generated by Django 5.2.4 on 2025-08-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_status_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
