# Generated by Django 5.2.4 on 2025-08-28 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_subscribers'),
        ('users', '0004_user_new_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribers_to', through='friends.Subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
