# Generated by Django 5.2.4 on 2025-08-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_email_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
