# Generated by Django 5.2.4 on 2025-09-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_new_email_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_video',
            field=models.FileField(blank=True, null=True, upload_to='covers/videos/', verbose_name='Відео-обкладинка'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Зображення-обкладинка'),
        ),
    ]
