# Generated by Django 5.2.4 on 2025-09-19 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_cover_video_alter_user_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cover_video',
        ),
    ]
