# Generated by Django 5.2.4 on 2025-08-28 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers_relations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Підписник',
                'verbose_name_plural': 'Підписники',
                'constraints': [models.UniqueConstraint(fields=('user', 'channel'), name='unique_subscription')],
            },
        ),
    ]
