# Generated by Django 5.2.4 on 2025-09-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='avatar',
            field=models.ImageField(blank=True, default='group_avatars/default_group.png', null=True, upload_to='group_avatars/'),
        ),
    ]
