# Generated by Django 5.2.4 on 2025-09-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_group_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppost',
            name='title',
            field=models.CharField(default='No title', max_length=80),
            preserve_default=False,
        ),
    ]
