# Generated by Django 5.2.4 on 2025-09-22 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_grouppost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='groups.groupcomment'),
        ),
    ]
