# Generated by Django 5.2.4 on 2025-09-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
